### ISSUE TITLE
Librairie étendue de calendrier républicain

### ISSUE THREAD

**Issue by popy-dev** [AlexisAmand/Imerologio#1]
J'ai développé il y a peu une librairie PHP de conversion de dates, ainsi qu'une implémentation du calendrier républicain.

Cette implémentation permet : 
* De dépasser l'an 20
* D'aller avant l'an 0 si nécéssaire
* D'afficher les nom des jours (chaque jour étant attribué à une plante, un outil, etc)

Ca pourrait donc être intéressant de (peut-être) l'utiliser pour le site

https://github.com/popy-dev/popy-calendar

**Comment by AlexisAmand** [comment]
Bonjour, 



Merci pour la proposition mais le site est avant tout destiné à des généalogistes qui sont en train de lire des documents anciens et qui ont besoin de convertir rapidement des dates officielles sur des documents. C'est pour cette raison que j'ai choisi de me limiter à la période de la révolution française où ce calendrier à été utilisé (je ne tiens pas compte de la commune de paris qui a utilisé ce calendrier).



Ps: Désolé pour la réponse tardive, je n'avais pas vu le message.
